Reorder month headers in earnings report
SkillsFundingAgency/das-provider-funding-web pull request #9
Opened 2023-02-08 09:02 UTC by dinathain

2023-02-08 10:50 UTC, MichaelYoung1981 reviewed
I suspect (and I could be wrong!) that the order of the properties in AcademicYearEarningsReport will also need to change.

2023-02-08 14:27 UTC, MichaelYoung1981 requested changes
Total needs to stay at the end.

2023-02-08 14:59 UTC, MichaelYoung1981 approved these changes

2023-02-09 10:53 UTC, tom-gough approved these changes

2023-02-09 10:54 UTC, merged